# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables: 
    CI_PROJECT_PATH: "C:/xampp/htdocs/test" 
    CI_COMPOSER_INSTALL_ARGS: "--no-interaction --optimize-autoloader"

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building the application..." 
    - composer install --no-interaction --optimize-autoloader

deploy-job: # This job runs in the deploy stage. 
  stage: deploy 
  script: 
      - echo "Deploying application..." 
      - $TEMP_BUILD_DIR="C:\temp_build" 
      - New-Item -Path $TEMP_BUILD_DIR -ItemType Directory -Force
      - Copy-Item -Path .\* -Destination $TEMP_BUILD_DIR -Recurse
      - Copy-Item -Path "$TEMP_BUILD_DIR\*" -Destination "$CI_PROJECT_PATH" -Recurse -Force
